# PyTorch - Tensors

This notebook explores basic tensors from PyTorch, how they work and how to operate them. 

In [2]:
import pandas as pd
import torch
print(torch.__version__)

2.2.2


# What is a Tensor?
Tensors are the fundamental build blocks of Machine Learning models in PyTorch. They are multidimensional arrays that can store data in various forms, such as scalars, vectors, matrices and high-dimensional arrays. Tensors enable efficient computation and are essential for performing mathematical operations and training models.

In PyTorch, we use tensors to encode the inputs and outputs of a model, as well as the model’s parameters. Tensors are similar to NumPy’s ndarrays, except that tensors can run on GPUs or other hardware accelerators. 

For more information, check the PyTorch documentation [here](https://pytorch.org/tutorials/beginner/basics/tensorqs_tutorial.html)

In [27]:
# Scalar
scalar_tensor = torch.tensor(5)
print(type(scalar_tensor))
print(scalar_tensor.ndim)
print(scalar_tensor.shape)
print(scalar_tensor)

<class 'torch.Tensor'>
0
torch.Size([])
tensor(5)


In [28]:
# Vector
vector_tensor = torch.tensor([1,0,0,1])
print(type(vector_tensor))
print(vector_tensor.ndim)
print(vector_tensor.shape)
print(vector_tensor)

<class 'torch.Tensor'>
1
torch.Size([4])
tensor([1, 0, 0, 1])


In [29]:
# Array
array_tensor = torch.tensor([[1, 0 ],[2,3]])
print(type(array_tensor))
print(array_tensor.ndim)
print(array_tensor.shape)
print(array_tensor)

<class 'torch.Tensor'>
2
torch.Size([2, 2])
tensor([[1, 0],
        [2, 3]])


In [37]:
# Generate random Tensor
random_tensor = torch.rand((4, 2, 2)) # 4 Rows, 2 Columns, 2 Matrices
print(type(random_tensor))
print(random_tensor.ndim)
print(random_tensor.shape)
print(random_tensor)

<class 'torch.Tensor'>
3
torch.Size([4, 2, 2])
tensor([[[0.1265, 0.8462],
         [0.5871, 0.0689]],

        [[0.3306, 0.2863],
         [0.9366, 0.6082]],

        [[0.5020, 0.7314],
         [0.8382, 0.7442]],

        [[0.6034, 0.5857],
         [0.3422, 0.9183]]])


In [43]:
# Generate a Tensor of ones or zeros
ones_tensor = torch.ones((4,2,2))
print(ones_tensor)
zeros_tensor = torch.zeros((4,2,2))
print(zeros_tensor)

tensor([[[1., 1.],
         [1., 1.]],

        [[1., 1.],
         [1., 1.]],

        [[1., 1.],
         [1., 1.]],

        [[1., 1.],
         [1., 1.]]])
tensor([[[0., 0.],
         [0., 0.]],

        [[0., 0.],
         [0., 0.]],

        [[0., 0.],
         [0., 0.]],

        [[0., 0.],
         [0., 0.]]])


# Tensors Operations

Like any NumPy array, Tensors can be applied to multiple operations. Here, we will cover the basics:
- Resizing
- Casting
- Matrix Multiplications
All these operations are based on NumPy operations.

Note that all Tensors need to be inside the same device (CPU or GPU) in order to be operated together. 

In [38]:
# Resizing
random_tensor.view(2, 2, 4)

tensor([[[0.1265, 0.8462, 0.5871, 0.0689],
         [0.3306, 0.2863, 0.9366, 0.6082]],

        [[0.5020, 0.7314, 0.8382, 0.7442],
         [0.6034, 0.5857, 0.3422, 0.9183]]])

In [49]:
# Casting
# On definition
float_tensor = torch.tensor([2.5, 5.3, 2.6], dtype=torch.float16)
float_tensor

tensor([2.5000, 5.3008, 2.5996], dtype=torch.float16)

In [50]:
# After definition
int_tensor = float_tensor.to(torch.int8)
int_tensor

tensor([2, 5, 2], dtype=torch.int8)

In [51]:
# Element-wise Product
float_tensor * float_tensor

tensor([ 6.2500, 28.0938,  6.7578], dtype=torch.float16)

In [54]:
# Matrix Multiplications
torch.matmul(float_tensor, float_tensor)

tensor(41.0938, dtype=torch.float16)